services:
  web:
      build: .
      ports:
        - "8080:80"
      restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx ayarları
      - ./certs:/etc/letsencrypt # SSL sertifikalarını saklama yeri
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt # SSL sertifikaları
      - ./html:/var/www/html # Let's Encrypt doğrulaması için
