services:
  
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Nginx ayarları
      - ./certs:/etc/letsencrypt                    # SSL sertifikaları
      - ./html:/usr/share/nginx/html               # Statik dosyalar
    restart: always